---
title: "Midterm 2"
author: "Bailey Burdick"
date: "2022-11-16"
output: html_document
---
```{r}
library(readr)
library(tidyverse)
library(knitr)
library(maps)
library(ggthemes)

earthquake_record_1965_2016 <- read_csv("earthquake_record_1965_2016.csv")
```
# Data handling
```{r}
DF_earthquake <- earthquake_record_1965_2016 %>% 
  filter(Type == "Earthquake") %>% 
    select(Date, Magnitude, Depth, Latitude, Longitude, `Magnitude Type`, Type) %>% 
    mutate(Date = as.Date(Date, "%m/%d/%Y"))

   DF_earthquake$Year <- as.numeric(format(DF_earthquake$Date, "%Y"))
```
**Making the Year column from the Date column, filtering by type, and mutating the date**

```{r}
mag_depth <- DF_earthquake %>%
    filter(Date >= '1974-01-01',
           Date <= '1994-01-01')
  

depthDF <- DF_earthquake %>%
    filter(Date >= '1974-01-01',
           Date <= '1994-01-01') %>% 
  group_by(Year) %>%
  summarize(maxDepth = max(Depth),
            minDepth = min(Depth),
            sdDepth = sd(Depth))

count_20yrs <- DF_earthquake %>% 
    filter(Date >= '1974-01-01',
           Date <= '1994-01-01') %>% 
    count(Year)

count_depth <- depthDF %>% 
  inner_join(count_20yrs, by = "Year")
```

## Graph 1
```{r}
depthGraph<-ggplot(count_depth)+
  geom_col(aes(x=Year, y=maxDepth), fill = "gray65")+
  geom_col(aes(x=Year, y=sdDepth), fill = "forestgreen")+
  geom_line(aes(x=Year, y=sdDepth), color = "black")+
  theme_minimal()+
    labs(title = "Maximum and Standard Deviation of Earthquake Depth: 1974-1994",
       subtitle = "Does the implementation of The Global Seismographic Network help detect earthquake depth?")+
  annotate("text", x=1974, y=400, label="Overall, in the 10 years following\nthe implementation, it is observed that the\ndetection of earthquake depth becomes\nmore consistent and has less variance",hjust = 0, size = 3, color="black")+
  annotate("segment", x = 1981.8, xend = 1983.5, y = 700, yend = 690, size = .75, arrow = arrow(), color = "blue")+
  annotate("text", x=1985, y=740, label="1984 - The Global Seismographic\n Network is Initiated", size = 3, color="blue")+
  annotate("text", x=1990, y=40, label="Standard Deviation", size = 4, color="gray5")+
    annotate("text", x=1990, y=300, label="Maximum", size = 4, color="gray5")+

  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        plot.subtitle = element_text(family="serif"),
        plot.title = element_text(family="serif"),
        plot.caption = element_text(family="serif"),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())

depthGraph
```

## Graph 2
```{r}
zoomed_graph <- ggplot(count_depth)+
  geom_col(aes(x=Year, y=n), fill = "gray65")+
  geom_line(aes(x=Year, y=n), color = "red")+
  theme_minimal()+
  annotate("text", x=1985, y=550, label="1984 - The Global Seismographic\n Network is Initiated", size = 3, color="blue")+
  annotate("text", x=1973, y=500, label="Overall, in the 10 years following the\nimplementation, it is observed that the detection\nof earthquakes becomes more consistent",hjust = 0, size = 3, color="gray20")+
    annotate("segment", x = 1985.8, xend = 1984, y = 516, yend = 483, size = .75, arrow = arrow(), color = "blue")+
  labs(title = "Number of Earthquakes Over Time: 1974-1994",
       subtitle = "Does the implementation of The Global Seismographic Network help detect earthquakes?",
       caption = "The 20 year span is chosen to show the trend before and the immediate trend after")+
      theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        plot.subtitle = element_text(family="serif"),
        plot.title = element_text(family="serif"),
        plot.caption = element_text(family="serif"),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())

zoomed_graph

```

```{r}
countEarthquakes <- DF_earthquake %>% 
  count(Year) %>% 
  mutate(NumEarthquakes = n) %>% 
  select(Year, NumEarthquakes)
```
**Making the count variable**

## Graph 3
```{r}
big_graph<-ggplot(countEarthquakes)+
  geom_line(aes(x=Year, y=NumEarthquakes)) +
  theme_minimal()+
   annotate("text", x=1981, y=590, label="1984 - The Global Seismographic Network is Initiated", size = 3, color="blue")+
    annotate("segment", x = 2005, xend = 2010, y = 650, yend = 650, size = .75, arrow = arrow(), color = "sienna")+
    annotate("segment", x = 1978, xend = 1984, y = 550, yend = 500, size = .75, arrow = arrow(), color = "blue")+
    annotate("text", x=2005, y=700, label="2011: 713 earthquakes", size = 3, color="sienna")+
     labs(title = "Number of Earthquakes Over Time",
       subtitle = "NOTE: Number of earthquakes may be increasing due to improved technology",
       caption = "Annotation source: https://earthquake.usgs.gov/education/eqscience-timeline.php")+
    theme(axis.title.x = element_blank(),
         axis.title.y = element_blank(),
        plot.subtitle = element_text(family="serif"),
        plot.title = element_text(family="serif"),
        plot.caption = element_text(family="serif"),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())
  
big_graph
```

## Making the dashboard
```{r}
library(patchwork)

final.dashboard<-big_graph / (zoomed_graph | depthGraph)+
  plot_annotation(
    title = 'How Successful was the implementation of The Global Seismographic Network?',
    subtitle = 'Global Seismographic Network: permanent digital network of seismometers that measure the vibrations of the world (USGS).\nOverall, the implementation of GSN was successful. It helped earthquake detection become more consistent and have less variance.',
    caption = 'Data Source: National Earthquake Information Center\nGSN Source: https://pubs.usgs.gov/fs/2011/3021/pdf/fs2011-3021.pdf')+
  plot_layout(heights=c(3.5, 3.5))+
  theme(plot.margin = 4)

ggsave(plot=final.dashboard, filename="Midterm2Graph.png",
       width=13, height=9.5, dpi=300)
```

